name: Render RMarkdown to HTML

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R environment
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.x'

    - name: Install dependencies
      run: |
        Rscript -e "install.packages('rmarkdown')"
        Rscript -e "install.packages('knitr')"
        Rscript -e "install.packages('tidyverse')"
        Rscript -e "install.packages('ggplot2')"

    - name: Render RMarkdown to HTML
      run: Rscript -e "rmarkdown::render('recipes.rmd', output_format = 'html_document')"

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update rendered HTML"
        git push
