name: Render and Deploy Recipe Book

on:
  push:
    branches:
      - main

jobs:
  render_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Render RMarkdown Document
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: recipes.rmd
          output_format: html_document

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
